### PR TITLE
Feature/packages

### PR DESCRIPTION
**Pull request by drd**

### CODE REVIEW

**Comment by drd** [comment]
TODO:
- [ ] update docs
- [ ] make subpackage build scripts work
- [ ] tests for react conformist
- [ ] import/export react-conformist into/from the base package
- [ ] publish all the things to npm

@carrbs @bauerca @bendman Any other TODOs?

**Comment by bauerca** [comment]
:+1: great start. No other todos from me at the moment.

**Comment by carrbs** [comment]
👍

**Comment by drd** [comment]
👋

**Pull request closed without merging**
